package com.ruanyun.chezhiyi.commonlib.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Unique;

/**
 * Entity mapped to table "ACCOUNT_INFO".
 */
@Entity
public class AccountInfo {

    @Id
    private Long id;
    private String loginName;
    private String passWord;
    @Unique
    private String userNum;

    public String getUserNum() {
        return this.userNum;
    }
    public void setUserNum(String userNum) {
        this.userNum = userNum;
    }
    public String getPassWord() {
        return this.passWord;
    }
    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }
    public String getLoginName() {
        return this.loginName;
    }
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }
    public Long getId() {
        return this.id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    @Generated(hash = 382892484)
    public AccountInfo(Long id, String loginName, String passWord, String userNum) {
        this.id = id;
        this.loginName = loginName;
        this.passWord = passWord;
        this.userNum = userNum;
    }
    @Generated(hash = 1230968834)
    public AccountInfo() {
    }
}
