package com.ruanyun.chezhiyi.commonlib.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.NotNull;
import org.greenrobot.greendao.annotation.Unique;
import org.greenrobot.greendao.annotation.Generated;

/**
 * Entity mapped to table "HX_GROUP".
 */
@Entity
public class HxGroup {

    /** Not-null value. */

    private String groupNum;
    @NotNull @Unique
    private String userNum;
    private String groupName;
    private Integer groupTotalNum;

    public Integer getGroupTotalNum() {
        return this.groupTotalNum;
    }

    public void setGroupTotalNum(Integer groupTotalNum) {
        this.groupTotalNum = groupTotalNum;
    }

    public String getGroupName() {
        return this.groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getUserNum() {
        return this.userNum;
    }

    public void setUserNum(String userNum) {
        this.userNum = userNum;
    }

    public String getGroupNum() {
        return this.groupNum;
    }

    public void setGroupNum(String groupNum) {
        this.groupNum = groupNum;
    }

    @Generated(hash = 1134153472)
    public HxGroup(String groupNum, @NotNull String userNum, String groupName, Integer groupTotalNum) {
        this.groupNum = groupNum;
        this.userNum = userNum;
        this.groupName = groupName;
        this.groupTotalNum = groupTotalNum;
    }

    @Generated(hash = 620598731)
    public HxGroup() {
    }
    
}
