package com.ruanyun.chezhiyi.commonlib.data.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ruanyun.chezhiyi.commonlib.model.AccountInfo;
import com.ruanyun.chezhiyi.commonlib.model.CarModel;
import com.ruanyun.chezhiyi.commonlib.model.HomeIconInfo;
import com.ruanyun.chezhiyi.commonlib.model.HxGroup;
import com.ruanyun.chezhiyi.commonlib.model.HxUser;
import com.ruanyun.chezhiyi.commonlib.model.HxUserGroup;
import com.ruanyun.chezhiyi.commonlib.model.ParentCodeInfo;
import com.ruanyun.chezhiyi.commonlib.model.ProjectType;
import com.ruanyun.chezhiyi.commonlib.model.RemindInfo;

import com.ruanyun.chezhiyi.commonlib.data.db.AccountInfoDao;
import com.ruanyun.chezhiyi.commonlib.data.db.CarModelDao;
import com.ruanyun.chezhiyi.commonlib.data.db.HomeIconInfoDao;
import com.ruanyun.chezhiyi.commonlib.data.db.HxGroupDao;
import com.ruanyun.chezhiyi.commonlib.data.db.HxUserDao;
import com.ruanyun.chezhiyi.commonlib.data.db.HxUserGroupDao;
import com.ruanyun.chezhiyi.commonlib.data.db.ParentCodeInfoDao;
import com.ruanyun.chezhiyi.commonlib.data.db.ProjectTypeDao;
import com.ruanyun.chezhiyi.commonlib.data.db.RemindInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountInfoDaoConfig;
    private final DaoConfig carModelDaoConfig;
    private final DaoConfig homeIconInfoDaoConfig;
    private final DaoConfig hxGroupDaoConfig;
    private final DaoConfig hxUserDaoConfig;
    private final DaoConfig hxUserGroupDaoConfig;
    private final DaoConfig parentCodeInfoDaoConfig;
    private final DaoConfig projectTypeDaoConfig;
    private final DaoConfig remindInfoDaoConfig;

    private final AccountInfoDao accountInfoDao;
    private final CarModelDao carModelDao;
    private final HomeIconInfoDao homeIconInfoDao;
    private final HxGroupDao hxGroupDao;
    private final HxUserDao hxUserDao;
    private final HxUserGroupDao hxUserGroupDao;
    private final ParentCodeInfoDao parentCodeInfoDao;
    private final ProjectTypeDao projectTypeDao;
    private final RemindInfoDao remindInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountInfoDaoConfig = daoConfigMap.get(AccountInfoDao.class).clone();
        accountInfoDaoConfig.initIdentityScope(type);

        carModelDaoConfig = daoConfigMap.get(CarModelDao.class).clone();
        carModelDaoConfig.initIdentityScope(type);

        homeIconInfoDaoConfig = daoConfigMap.get(HomeIconInfoDao.class).clone();
        homeIconInfoDaoConfig.initIdentityScope(type);

        hxGroupDaoConfig = daoConfigMap.get(HxGroupDao.class).clone();
        hxGroupDaoConfig.initIdentityScope(type);

        hxUserDaoConfig = daoConfigMap.get(HxUserDao.class).clone();
        hxUserDaoConfig.initIdentityScope(type);

        hxUserGroupDaoConfig = daoConfigMap.get(HxUserGroupDao.class).clone();
        hxUserGroupDaoConfig.initIdentityScope(type);

        parentCodeInfoDaoConfig = daoConfigMap.get(ParentCodeInfoDao.class).clone();
        parentCodeInfoDaoConfig.initIdentityScope(type);

        projectTypeDaoConfig = daoConfigMap.get(ProjectTypeDao.class).clone();
        projectTypeDaoConfig.initIdentityScope(type);

        remindInfoDaoConfig = daoConfigMap.get(RemindInfoDao.class).clone();
        remindInfoDaoConfig.initIdentityScope(type);

        accountInfoDao = new AccountInfoDao(accountInfoDaoConfig, this);
        carModelDao = new CarModelDao(carModelDaoConfig, this);
        homeIconInfoDao = new HomeIconInfoDao(homeIconInfoDaoConfig, this);
        hxGroupDao = new HxGroupDao(hxGroupDaoConfig, this);
        hxUserDao = new HxUserDao(hxUserDaoConfig, this);
        hxUserGroupDao = new HxUserGroupDao(hxUserGroupDaoConfig, this);
        parentCodeInfoDao = new ParentCodeInfoDao(parentCodeInfoDaoConfig, this);
        projectTypeDao = new ProjectTypeDao(projectTypeDaoConfig, this);
        remindInfoDao = new RemindInfoDao(remindInfoDaoConfig, this);

        registerDao(AccountInfo.class, accountInfoDao);
        registerDao(CarModel.class, carModelDao);
        registerDao(HomeIconInfo.class, homeIconInfoDao);
        registerDao(HxGroup.class, hxGroupDao);
        registerDao(HxUser.class, hxUserDao);
        registerDao(HxUserGroup.class, hxUserGroupDao);
        registerDao(ParentCodeInfo.class, parentCodeInfoDao);
        registerDao(ProjectType.class, projectTypeDao);
        registerDao(RemindInfo.class, remindInfoDao);
    }
    
    public void clear() {
        accountInfoDaoConfig.clearIdentityScope();
        carModelDaoConfig.clearIdentityScope();
        homeIconInfoDaoConfig.clearIdentityScope();
        hxGroupDaoConfig.clearIdentityScope();
        hxUserDaoConfig.clearIdentityScope();
        hxUserGroupDaoConfig.clearIdentityScope();
        parentCodeInfoDaoConfig.clearIdentityScope();
        projectTypeDaoConfig.clearIdentityScope();
        remindInfoDaoConfig.clearIdentityScope();
    }

    public AccountInfoDao getAccountInfoDao() {
        return accountInfoDao;
    }

    public CarModelDao getCarModelDao() {
        return carModelDao;
    }

    public HomeIconInfoDao getHomeIconInfoDao() {
        return homeIconInfoDao;
    }

    public HxGroupDao getHxGroupDao() {
        return hxGroupDao;
    }

    public HxUserDao getHxUserDao() {
        return hxUserDao;
    }

    public HxUserGroupDao getHxUserGroupDao() {
        return hxUserGroupDao;
    }

    public ParentCodeInfoDao getParentCodeInfoDao() {
        return parentCodeInfoDao;
    }

    public ProjectTypeDao getProjectTypeDao() {
        return projectTypeDao;
    }

    public RemindInfoDao getRemindInfoDao() {
        return remindInfoDao;
    }

}
